# -*- coding: utf-8 -*-
"""real_estate_price_size_using_Regeression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11s2mVbryduGy_3OX6SlqkZB8fjoPsTnu
"""

!pip install numpy pandas matplotlib

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv("real_estate_price_size.csv")
df.head(15)

df.isna().sum()

df.info()

import matplotlib.pyplot as plt
plt.scatter(df['size'], df['price'], color='red')
plt.title('Scatter Plot: Size vs Price')
plt.xlabel('Size ')
plt.ylabel('Price')
plt.show()

x = df[['size']]
y = df['price']

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

print(regressor.intercept_)
print(regressor.coef_)

y_pred = regressor.predict(x_test)

from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

regressor.predict([[643.09]])

import matplotlib.pyplot as plt
plt.scatter(x_train,y_train,color='red')
plt.plot(x_test,y_pred,color="black")

from sklearn.metrics import mean_absolute_error as MAE
from sklearn.metrics import mean_squared_error as MSE
from sklearn.metrics import root_mean_squared_error as RMSE

print("MAE : ",MAE(y_test,y_pred))
print("MSE : ",MSE(y_test,y_pred))
print("RMSE : ",RMSE(y_test,y_pred))